### ISSUE TITLE
Are you aware of DOM package containing this already?

### ISSUE THREAD

**Issue by shurcooL** [emersion/go-js-canvas#1]
Hi,

I just want to check, are you aware of the GohperJS [DOM package](https://godoc.org/honnef.co/go/js/dom) (/cc @dominikh)? It already contains bindings for Canvas element (among many others).

https://godoc.org/honnef.co/go/js/dom#HTMLCanvasElement
https://godoc.org/honnef.co/go/js/dom#CanvasRenderingContext2D

Did you know that when making this package?

Thanks.

**Comment by shurcooL** [comment]
Hi @emersion, did you see this question?

**Comment by emersion** [comment]
Yeah, you're right. Thanks!
